version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres_pos
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
